### ISSUE TITLE
Content folder updates failing for private repositories

### ISSUE THREAD

**Issue by fbertsch** [mozilla/lookml-generator#188]
We run content folder generation twice, once for `spoke-default` and once for `spoke-private`. For the latter, we're running in to an error when we try and delete all permissions:
```
[2021-07-29 17:39:44,500] {pod_launcher.py:156} INFO - b'Traceback (most recent call last):\n'
[2021-07-29 17:39:44,500] {pod_launcher.py:156} INFO - b'  File "/usr/local/bin/lookml-generator", line 33, in <module>\n'
[2021-07-29 17:39:44,500] {pod_launcher.py:156} INFO - b"    sys.exit(load_entry_point('lookml-generator', 'console_scripts', 'lookml-generator')())\n"
[2021-07-29 17:39:44,500] {pod_launcher.py:156} INFO - b'  File "/app/lookml-generator/generator/__main__.py", line 9, in main\n'
[2021-07-29 17:39:44,500] {pod_launcher.py:156} INFO - b'    cli("generator")\n'
[2021-07-29 17:39:44,500] {pod_launcher.py:156} INFO - b'  File "/app/lookml-generator/generator/__init__.py", line 37, in cli\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'    group(prog_name=prog_name)\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'    return self.main(*args, **kwargs)\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1062, in main\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'    rv = self.invoke(ctx)\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'    return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'    return ctx.invoke(self.callback, **ctx.params)\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 763, in invoke\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'    return __callback(*args, **kwargs)\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'  File "/app/lookml-generator/generator/content.py", line 157, in generate_content\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'    generate_folders(yaml.safe_load(namespaces))\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'  File "/app/lookml-generator/generator/content.py", line 107, in generate_folders\n'
[2021-07-29 17:39:44,501] {pod_launcher.py:156} INFO - b'    sdk.delete_content_metadata_access(int(content_metadata_access.id))\n'
[2021-07-29 17:39:44,502] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/site-packages/looker_sdk/sdk/api31/methods.py", line 2028, in delete_content_metadata_access\n'
[2021-07-29 17:39:44,502] {pod_launcher.py:156} INFO - b'    self.delete(\n'
[2021-07-29 17:39:44,502] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/site-packages/looker_sdk/rtl/api_methods.py", line 233, in delete\n'
[2021-07-29 17:39:44,502] {pod_launcher.py:156} INFO - b'    return self._return(response, structure)\n'
[2021-07-29 17:39:44,502] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/site-packages/looker_sdk/rtl/api_methods.py", line 87, in _return\n'
[2021-07-29 17:39:44,502] {pod_launcher.py:156} INFO - b'    raise error.SDKError(response.value.decode(encoding=encoding))\n'
[2021-07-29 17:39:44,502] {pod_launcher.py:156} INFO - b'looker_sdk.error.SDKError: {"message":"Cannot remove access for User DataSRE Automation CircleCI with edit on parent","documentation_url":"http://docs.looker.com/"}\n'
[2021-07-29 17:39:44,607] {pod_launcher.py:156} INFO - b'~/looker-spoke-private ~\n'
[2021-07-29 17:39:44,608] {pod_launcher.py:156} INFO - b'+ popd\n'
```

**Comment by fbertsch** [comment]
Fixed, we removed that user from the folders.
